language: csharp
solution: SampleTest.sln

script:
– xbuild /p:Configuration=Release SampleTest.sln
– mono ./testrunner/NUnit.Runners.3.10.1/tools/nunit-console.exe  ./SampleTest.Test/bin/Release/SampleTest.Test.dll
